export { routes as AdminRoutes } from "./admin";
export { routes as PelangganRoutes } from "./pelanggan";
export { routes as MenuRoutes } from "./menu";
export { routes as KeranjangRoutes } from "./keranjang";
export { routes as PemesananRoutes } from "./pemesanan";
export { routes as ChatRoutes } from "./chat";
export { routes as LogRoutes } from "./log";
export { routes as SettingRoutes } from "./setting";
export { routes as KomplainRoutes } from "./komplain";
